[package]
name = "simulations"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "*"
sdl2 = {version = "*", features = ["gfx"]}
